textileio/textile

cmd/textile/projects.go

just a small one. 
i was going to fix #42 as well but ended up proposing a slight reorg to the initial user flow first, https://github.com/textileio/textile/issues/65

Minor: Fixes #43

---

api/service.go

Signed-off-by: Aaron Sutula <hi@asutula.com>

get or create project for AddProject

---

api/client/client.go
api/server.go
api/service.go
cmd/textiled/main.go
collections/buckets.go
core/core.go
docker-compose.yml
gateway/bucketfs.go
gateway/gateway.go

- Creates a CNAME for each (global) bucket
- The gateway leverages the client to implement a simple _bucket file system_ for rendering static assets via a static middleware

Bucket CNAMES and Pages

---

api/client/client_test.go
cmd/textile/buckets.go
docker-compose.yml
gateway/gateway.go

Not much to see here, just showing a better user error when pushing to a bucket that already exists for a different scope.

Better bucket exists error

---

cmd/textile/buckets.go

Closes #80 
Pretty straightforward:
`textile buckets cat [path]`
Or redirect to file...
`textile buckets cat [path] > ./file`

Adds cat bucket path command

---

gateway/bucketfs.go

fixes https://github.com/textileio/textile/issues/111

Allows direct rendering of subdirectories in bucket gateway

---

gateway/bucketfs.go

Signed-off-by: andrew <andrew@textile.io>

buckets: fixes case of directory with no index.html

---

cmd/tt/buckets.go
cmd/tt/init.go
cmd/tt/login.go
cmd/tt/main.go

Signed-off-by: andrew <andrew@textile.io>

fix(cli): update help messages with new binary name

---

cmd/tt/buckets.go
cmd/tt/main.go

fixes https://github.com/textileio/textile/issues/152

chore(docs): update doc strings

---

Dockerfile
Makefile
go.mod
go.sum

* Rebuilds things if local code changed (that was the original intention of all this, missed flag)
* Changed Dockerfile to make rebuilds faster.
* mod tidy

make/local-up: rebuild image on code change & Dockerfile optimization

---

api/buckets/service.go
cmd/tt/main.go
gateway/ipfs.go
util/util.go

Closes #201 
Closes #196 
Closes #133

Buckets: Transform roots to Cid V1

---

api/buckets/service.go
buckets/buckets.go
cmd/buckd/docker-compose.yml
cmd/hubd/docker-compose.yml

Small one here... catches invalid schema errors and force updates the collection.

Handle collection updates

---

README.md

docs: tt -> hub

---

cmd/hubd/main.go

hubd: powergate config fix

---

cmd/buck/cli/archive.go
cmd/cmd.go
integrationtest/pg/docker-compose.yml
integrationtest/pg/powcli/docker-compose-pow.yml

While writing the Blog article draft, I fixed some deadline nits, and updated to newest PG and Devnet with the feature mentioned in the article.

pg integration: small fixes and image updates

---

go.mod
go.sum

mod: updates threads to v0.1.21

---

api/buckets/service.go

Uses built-in node resolver when the bucket is not encrypted.

Fix plaintext pull path

---

api/buckets/service.go
cmd/buck/cli/init.go
go.mod

- Migrates existing dag encryption to an iterative solution
- Migrates existing dad encryption to handle leaf nodes in parallel
Closes #246

Iteratively encrypt existing dags

---

buckets/local/bucket.go
buckets/local/bucket_test.go

Fixes nodes comparison where one of the nodes is a _file_ (proto) node, which contain only unnamed links to raw blocks.

local: fix local diffing with file nodes

---

api/buckets/client/client_test.go
cmd/buck/cli/add.go
cmd/buckd/docker-compose-dev.yml
cmd/buckd/docker-compose.yml
cmd/hubd/docker-compose-dev.yml
cmd/hubd/docker-compose.yml
go.mod
go.sum
integrationtest/pg/docker-compose.yml
integrationtest/pg/powcli/docker-compose-pow.yml

Update to latest Powergate, and IPFS v0.6.0.
I'm still targeting to `master` since I feel we're still at the stage of every commit being quite useful.
Maybe when things slow down we could stick to releases.

chore: update pow and ipfs

---

core/core.go

We are currently running Textile on users computer and we noticed some computers (mostly macOS which has a default open file descriptor limit of 256) eventually start erroring with a `too many files open` error. 
Investigation shows that threads was opening a lot of connections and this was taking up all the file descriptor limits.
This PR exposes a configuration option to allow updating the ConnectionManager passed to libp2p. This would allow users to control low and high connection watermarks [like it is done here](https://github.com/textileio/go-threads/blob/b50ac33e1bd7dcf7e61605de296fd70614b6a805/threadsd/main.go#L72).

Feature: Configure Threads P2P Connection Manager

---

core/core.go
go.mod
go.sum

mod: update threads to master

---

go.mod
go.sum

mod: bump threads to v0.1.23

---

api/buckets/service.go

Buckets: replace filepath with path in service

---

README.md

docs: ensure hub is enabled when creating mail lib

---

api/buckets/service.go

Stops creating a CNAME for each bucket.

dns: dont create bucket cnames

---

cmd/buck/cli/cli.go

The old buck org flag was lingering around...

Fix buck init org

---

.github/workflows/release.yml
.github/workflows/test.yml

fix(ci): uses built gox

---

buckets/local/archive.go
cmd/buck/cli/archive.go

The original gRPC error is a bit criptic and might leave the sensation something went wrong with the archive when that isn't the case. 
Prelim screenshot of result:

explain better RST gRPC msg

---

cmd/buck/cli/archive.go
cmd/buck/cli/cli.go
cmd/buck/cli/init.go
cmd/buck/cli/pull.go
cmd/buck/cli/push.go
core/core.go

Closes #355 
Closes #350
Closes #351

Remove WS ping and add some requested buck flags

---

api/buckets/client/client_test.go
api/buckets/service.go
core/core.go

Adds the semaphore mechanism used in `go-threads` to ensure buckets are not concurrently altered.

buckets: adds bucket-wide locks

---

README.md
buckets/local/archive.go
cmd/buck/cli/archive.go
mongodb/bucketarchives.go

fix(cli): quickfix testnet term

---

api/billingd/service/service.go
cmd/hub/cli/billing.go

Micro nits. Not worthy of a review.

billing: couple little nits

---

api/billingd/client/client_test.go
api/billingd/main.go
api/billingd/service/service.go
api/bucketsd/service.go
core/usage_interceptor.go

Closes #390
- Better stored data tracking inside the buckets service
- Adds a `FreeQuotaGracePeriod` config param to `billingd`

More billing nits

---

api/usersd/pb/javascript/package.json
mongodb/migrations/migrations.go
mongodb/migrations/migrations_test.go

- Some cleanups from the migration deploy problem
- Includes the billing files in the user js package

Bump migration timeout

---

api/billingd/migrations/migrations.go
api/billingd/migrations/migrations_test.go
api/billingd/service/service.go
mongodb/migrations/migrations_test.go

Adds migrations functionality and one migration: _make customer_id index sparse_

billing: add db migrations

---

cmd/hubd/main.go
core/core.go

chore(env): update cmd

---

analytics/analytics.go
api/billingd/service/service.go

fix(analytics): unix seconds not nano; cron all products

---

cmd/hub/cli/billing.go

fix(cli): usage date string parsed incorrectly

---

api/bucketsd/client/client.go

- Normalize windows path in the _client_ if runtime is windows, e.g., `"node_modules\.bin\foo"` becomes `"node_modules/.bin/foo"`

buckets: normalize windows paths

---

api/bucketsd/service.go

Hotfix for these panics: https://grafana-v7.hub.next.textile.io/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22hub-production%2Fhub%5C%22%7D%22%7D%5D

Fix nil ctx

---

cmd/hub/cli/billing.go

fix(cli): small wording change to be explicit

---

cmd/buck/cli/init.go
cmd/buck/cli/util.go

- Don't use progress bar on windows
- Fix `buck init` (`unfreeze` flag used but not defined)

Hide progress on windows

---

api/hubd/service.go
core/usage_interceptor.go

fix(bug): rm user since possibly nil

---

api/mindexd/pb/mindexd.proto
api/mindexd/pb/mindexd.swagger.json

Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>

swagger: fix typo and link

---

cmd/hub/cli/fil.go

chore(ci): add messages about addrs and verification

---

api/billingd/gateway/gateway.go
api/bucketsd/service.go
cmd/buck/cli/watch.go

Nothing special just some things that were bugging me.

nits: follow up to #522

---

api/sendfild/main.go
api/sendfild/service/service.go

Pretty straight forward. If you don't want to be forced to provide an address list, you can opt out explicitly using another flag.

Allowed from addrs list

---

api/bucketsd/client/client.go

CLI improvement to allow faster ingestion of processed uploads.

buck push: unlock before send-chunk

---

gateway/ipfs.go

two more that we probably want to support browser rendering

feat(api): adds text/plain for txt and md types

---

cmd/buck/cli/archive.go

fix(cli): verified clients could be making 0FIL deals

---

api/billingd/main.go
api/mindexd/main.go
cmd/buckd/main.go
cmd/hubd/main.go
cmd/output.go

cmd: set default log level to info

---

api/mindexd/service/cast.go

Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>

mindexd: default sorting behaviour fix

---

.github/workflows/test.yml
api/apitest/docker-compose.yml
api/billingd/gateway/gateway.go
cmd/buckd/docker-compose-dev.yml
cmd/buckd/docker-compose.yml
cmd/hubd/docker-compose-dev.yml
cmd/hubd/docker-compose.yml
cmd/output.go
core/core.go
integrationtest/pg/docker-compose.yml
integrationtest/pg/powcli/docker-compose-pow.yml

ipfs: use v0.8.0 and log fix

---

go.mod
go.sum

Updates `go-threads` to include fix: https://github.com/textileio/go-threads/pull/522

mod: use go-threads hotfix

---

api/bucketsd/service.go

fix(errs): report current current delta.

---

api/billingd/service/service.go

Ensure that the billable parent customer is used in the usage interceptor.

billing: use parent when getting daily usage

---

go.mod
go.sum

threads: update to 1842e70155ecd1de686467cb7884d0f67673c529

---

go.mod
go.sum

threads: update to v1.1.3

---

buckets/archive/tracker/tracker.go
core/core.go

Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>

fil: avoid tracker and retrieval modules if archiving is disabled

---

README.md

Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

Update README with deprecation notice
