textileio/textile

- cmd/textiled/main.go
Signed-off-by: andrew <andrew@textile.io>
> flags: makes filecoin api address empty by default so not used

- cmd/textile/projects.go
- cmd/textile/teams.go
two changes here.
shows the arg required in the project init usage string,
```
Usage:
textile projects init [name] [flags]
```
removes the prompt flow in the `textile team add` so that it works the same as `textile project init` where you just pass the arg. so new usage is,
```
Usage:
textile teams add [name] [flags]
```
let me know if there was a strong preference for the old prompt flow of the second one, happy to rip that out if so
> cli: cleanup team and project methods

- docker-compose.yml
- gateway/gateway.go
Using `json=true` with the collection / instance URLs forces rendering the result as JSON, but it was broken.
> gateway: fix json mode

- api/buckets/pb/javascript/package.json
- api/hub/pb/javascript/package.json
- api/users/pb/javascript/package.json
Tiny 'nit' PR. If there is an argument against this, that's also fine. We use `*-grpc` in our other JS libs, it it seemed like a good idea to do the same here. Also, seems useful to reserve the top-level lib names (`hub`, `user`, `buckets`) for those actual clients (if we ever needed them), plus this avoids confusion when folks are installing via npm (they might try to install @textile/hub and get something unexpected).
> Rename js packages to match existing conventions

- Makefile
- docker-compose-dev.yml
Created a `dev` compose file that doesn't rely on compiled `textile`, but local code. So you can change the code and run things again. (No .env things needed). This is a similar idea of the `make embed` in Powergate, which re-runs the docker-build on changed code.
The run is clean in the sense that *nothing* about the docker-compose run is mapped to the local HDD, all lives inside docker volumes.
I added new `make` commands:
- `make local-up`: spin up things with `textile` running local code.
- `make local-stop`: to stop things, but keep volumes (state).
- `make local-clean`: clean all things, so next `local-up` is a fresh world. We could go a step further and also do `rm -r ~/.textile` to rm any client folder... but preferred to leave the host folder untouched just in case the client …
> run dev locally in single commands

- api/buckets/service.go
Ed25519 keys base32-encode to length 65, which is too long for Cloudflare's CNAME name entry (max 63). 2048 bit RSA keys base32-encode to length 59.
> IPNS: Use RSA keys which encode to shorter strings

- cmd/tt/bucket.go
`.` directory was being stripped from the path when determining local path.
> Fix pull root-level hidden files

- api/hub/service.go
- cmd/cmd.go
- cmd/tt/bucket.go
- cmd/tt/destroy.go
- cmd/tt/keys.go
- cmd/tt/orgs.go
- cmd/tt/threads.go
- collections/accounts.go
- collections/accounts_test.go
- core/core.go
Closes #171 
Closes #179  
Closes #191 
- Improves the UX around choosing a threadDB for a new bucket:
1. If the account (dev/org) has no DBs, they _are not_ given the option of naming the DB... it will be called "default"
2. Next time they need to choose a DB, the "default" one is shown on top
3. If they choose to create a new one, they are then asked what to name it
- Adds `tt bucket destroy`
- Improves UX with _dangerous_ actions like,
- `tt destroy`: Dev must type their username
- `tt orgs destroy`: Dev must type the full name of the org
- `tt bucket destroy`: Dev must confirm
- Fixes `tt threads` and `tt keys` to use the `--org` flag when present (it will still pick up the config setting within a bucket, but the flag will always override)
- Adds a conditional on account deletion: …
> Adds destroy bucket command and some other nits

- .github/workflows/release.yml
Temporarily avoid windows build errors related to sector storage.
> ci: dont built for windows

- api/buckets/client/client.go
- api/buckets/pb/buckets.pb.go
- api/buckets/pb/buckets.proto
- api/buckets/service.go
- buckets/buckets.go
- buckets/local/bucket.go
- buckets/local/bucket_test.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
- cmd/buck/cli/pull.go
- cmd/buck/cli/push.go
- cmd/buck/cli/root.go
- cmd/buck/cli/status.go
- cmd/buck/cli/util.go
- cmd/buckd/main.go
- cmd/hub/cli/init.go
- cmd/hub/cli/login.go
- cmd/hubd/main.go
- integrationtest/pg/pg_test.go
I ran into the issue where I could not get to an "up-to-date" state locally since the local bucket was constructing a cid v1 tree.
- Allows a local bucket to be either cid v0 or cid v1
- Detects remote cid version when needed locally
- Handles bucket schema updates when creating a new bucket in an older thread
> Support cid v0 local buckets

- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
Fixes a typo and improves CLI bucket `init` description.
> docs: typos and improved cli description

- core/core.go
Signed-off-by: Aaron Sutula <hi@asutula.com>
> enable keepalive pinging

- api/apitest/apitest.go
- api/buckets/client/client_test.go
- api/users/client/client_test.go
- buckets/local/bucket_test.go
- buckets/local/buckets_test.go
- buckets/local/options.go
- buckets/local/pull.go
- buckets/local/push.go
- buckets/local/watch.go
- cmd/buck/cli/add.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
- cmd/buck/cli/pull.go
- cmd/buck/cli/push.go
- cmd/buck/cli/util.go
- cmd/buck/cli/watch.go
- cmd/buckd/main.go
- cmd/hubd/main.go
- cmd/output.go
- core/core.go
- go.mod
- go.sum
- integrationtest/pg/pg_test.go
Closes #275 
This is the missing piece of the _offline-first_ bucket sync w/ diffing functionality. From the `Watch` docstring: 
```
// Watch watches for and auto-pushes local bucket changes at an interval,
// and listens for and auto-pulls remote changes as they arrive.
// This will survive connectivity interruptions.
// Returns a channel of watch connectivity states. Cancel context to stop watching.
```
Demo: https://bafk7wyub5byqrryei4wbb7smmwqhiiuyhikyxu36o5rq4vixnwkwhia.thread.hub.textile.io/buckets/bafzbeib5zrflczb5scupkw2xd3277yxxycpdsre2uiwzzth3s2t2duljbm/watch_offline.mp4
> Offline-first bucket watch

- api/buckets/service.go
- buckets/archive/tracker.go
- buckets/local/buckets_test.go
- buckets/local/options.go
- buckets/local/watch.go
- core/core.go
- go.sum
- integrationtest/pg/pg_test.go
- mail/local/mailbox_test.go
- mongodb/archivetracking.go
- mongodb/archivetracking_test.go
- mongodb/collections.go
- threaddb/buckets.go
- threaddb/threaddb.go
Closes #282, which already has an explanation of the intention of the change.
The gateway token was promoted to a more general concept. It is (and will be) used as an internal session to bypass auth interceptor in any internal logic of the Hub. This avoids the need of having to serialize auth information from dev/org/user and recover it out-of-request to perform actions on threads on its behalf.
> pg: archive tracker component

- api/users/client/client.go
- api/users/client/client_test.go
- api/users/pb/users.pb.go
- api/users/pb/users.proto
- api/users/service.go
- core/core.go
- mail/local/mail.go
- mail/local/mailbox.go
- mail/mail.go
- threaddb/buckets.go
- threaddb/mail.go
- threaddb/threaddb.go
This changes the internal mailbox handling to use a single thread per user instead of one for an inbox and one for a sentbox.
> Mail: use a single thread per user

- api/buckets/client/client.go
After some tests, it improves the upload speed since more volume of real data is sent per roundtrip to the Hub.
Improves uploading speed using the CLI.
> increase chunk size in buckets client

- api/buckets/service.go
- buckets/archive/tracker.go
- buckets/buckets.go
- core/core.go
- mongodb/bucketarchives.go
- mongodb/bucketarchives_test.go
- threaddb/buckets.go
This fixes an edge case where a Bucket exists before archiving was implemented so its `BucketArchive` record can't be found. Also removes the "ffs" wording from publicly exposed error messages and a couple places where "bucket archive" as incorrectly referred to as "ffs".
> GetOrCeate BucketArchive, better error messages

- README.md
Running `go get github.com/textileio/textile/cmd/hubd` outside of a Go module, that is in GOPATH mode, stumbles over a couple of dependencies.
* One can workaround libp2p/go-libp2p-asn-util#2 with `cd $GOPATH/github.com/libp2p/go-libp2p-asn-util && git checkout feat/init`.
* I didn't find a workaround for `package github.com/mailgun/mailgun-go/v3: cannot find package "github.com/mailgun/mailgun-go/v3"`, but I noticed https://proxy.golang.org/github.com/mailgun/mailgun-go/@v/list doesn't include any "v3".
```
$ go version
go version go1.14.7 linux/amd64
$ go env
GO111MODULE=""
[...]
GOPROXY="https://proxy.golang.org,direct"
[...]
```
> Update README.md about installing from source

- api/buckets/service.go
- buckets/archive/tracker.go
- core/core.go
Use `strings.Contains` to check for auth FFS recreation logic.
> Use contains to check for auth token not found

- buckets/archive/tracker.go
Consider another border case apart from FFS resets.
See https://github.com/textileio/powergate/pull/589.
> archive/tracker: fail if job is not found

- buckets/local/archive.go
Improve CLI experience allowing to print all logs on _watch_ mode if archive finished successfully.
> Allow to print archive logs on success

- core/core.go
Note: I updated our dev instance of the hub to use this version and it's working.  However when I run `go test ./...` it hangs.  I was able to compile `buckd` and `hubd` fine as well. Let me know if there are any steps to get all the tests working and if there are any other steps I should do before making the PR as per your local dev process.
> Hotfix/buckets-acl: use correct names in cross user method list.

- api/hub/service.go
- api/users/client/client_test.go
- buckets/local/bucket.go
- go.mod
- go.sum
Also fixes an issue where old buckets with `nil` `Metadata` caused a CLI panic.
> Update to threads w/ txn errors

- api/buckets/client/client_test.go
- api/buckets/service.go
- buckets/buckets.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/roles.go
- threaddb/buckets.go
Adds a new `buck roles` command with two sub-commands, `buck roles grant` and `buck roles ls`. Grant is used like,
```
buck roles grant [identity] [path]
```
Omitting `path` indicates the root. You can specify the role with `--role=none|reader|writer|admin`, otherwise a prompt appears.
> buck: adds role ls and roles grant cmds

- buckets/local/archive.go
- cmd/output.go
Looks like in some refactoring that extracted pb mappings, some assignment got missed.
I also changed the `cmd.RenderTable` that we use in many commands to be safe if the underlying data of the table is empty:
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/textileio/textile/cmd.RenderTable(0xc00073dd10, 0x2, 0x2, 0x0, 0x0, 0x0)
/home/runner/work/textile/textile/cmd/output.go:79 +0x336
```
I've seen in other parts that some commands check for `len(..) == 0` to avoid the `RenderTable` call, but I think is better to be on the safe side and don't panic in that case.
> cli: fix missing pb mapping & improve render table

- api/pow/client/client.go
- cmd/hub/cli/cli.go
- cmd/hub/cli/pow.go
- core/core.go
- integrationtest/pg/pow_client_test.go
Disables the call in the interceptor level and then in the client and CLI as well.
> Remove call to powergate new addr

- .github/workflows/publish-js-libs.yml
- Makefile
Github actions changed... can no longer use `set-env` or `add-path` commands without an env override. We'll want to upgrade to [the _new_ way](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) of doing this soon. Overriding for now.
> Fix releases

- api/billingd/client/client_test.go
- api/billingd/gateway/gateway.go
- api/billingd/main.go
- api/billingd/service/service.go
- api/bucketsd/client/client_test.go
- api/hubd/client/client_test.go
- api/usersd/client/client_test.go
- core/usage_interceptor.go
Fix for a nit I noticed while testing on staging. Usage for monthly incremental products was not showing usage for the current day, only historical for the month. Was only noticeable across multiple days of usage, which my staging account has.
> Tmp fix for current period usage

- buckets/local/diff.go
- buckets/local/push.go
- buckets/local/repo.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
- cmd/buck/cli/pull.go
- cmd/buck/cli/push.go
- cmd/buck/cli/roles.go
- cmd/buck/cli/util.go
- cmd/buck/cli/watch.go
- cmd/hub/cli/billing.go
- cmd/hub/cli/cli.go
- cmd/hub/cli/destroy.go
- cmd/hub/cli/init.go
- cmd/hub/cli/keys.go
- cmd/hub/cli/login.go
- cmd/hub/cli/orgs.go
- cmd/hub/cli/threads.go
- cmd/hub/cli/update.go
- cmd/hub/cli/version.go
- cmd/hub/cli/whoami.go
- cmd/output.go
This fixes multiples Hub CLI problems in Windows. 
There were three main problems:
- We had an assumption of `/` being the path separator, which is now changed to `runtime.OsPathSeparator` to be platform-independent.
- The `uiprogress` component used in pushing files doesn't work in Windows, it tries to use `stty` with error: `←[31m> Error! ←[90mExec: "stty": executable file not found in %!P(MISSING)ATH%!←(MISSING)[0m←[0m`. I changed to detect if that's the case and avoid using the component but explain the event with plain text. (see screenshot below).
- The Windows terminal doesn't support ANSI colors as explained in the `aurora` package we use for coloring terminal output. I changed the `aurora` reference to a custom instance which enables or disables coloring depending on the OS. …
> Fix Windows CLI problems

- .github/workflows/publish-js-libs.yml
- scripts/publish_js_protos.bash
It would be nice to do prereleases in GitHub and publish NPM artifacts to the `next` tag instead of overriding the `latest` tag. These changes should enable that.
> Prerelease to NPM

- api/billingd/gateway/gateway.go
- cmd/buckd/docker-compose-dev.yml
- cmd/buckd/docker-compose.yml
- cmd/hubd/docker-compose-dev.yml
- cmd/hubd/docker-compose.yml
- go.mod
- go.sum
- Updates `go-threads` to v1.0.2
- Since we're using real Stripe keys for staging and production, events from either env are received by both. This doesn't hurt anything, but it does mean that the webhook thinks it's unhealthy and is threatening to delete it. So, if the event fails our biz logic, we just log a warning and return 200. I'd like to create a different stripe account for staging so we can use _different_ live keys there. Then we can revert this change.
> go-threads v1.0.2

- api/filecoin/client/client.go
- cmd/hub/cli/cli.go
- cmd/hub/cli/fil.go
- core/core.go
Allows Slingshot participants using Hub bucket archives to sign messages for the competition. 
Closes #422
> Add Filecoin wallet sign and verify methods

- api/billingd/client/client_test.go
- api/billingd/service/service.go
- buckets/local/buckets_test.go
- mail/local/mailbox_test.go
Of course, an empty string is not considered "sparse" in a document... a downside of using Go structs with the mongo API: No way to omit a string field.
> billing: avoid empty customer string

- README.md
- analytics/analytics.go
- api/billingd/Dockerfile
- api/billingd/Dockerfile.dev
- api/billingd/gateway/gateway.go
- api/billingd/main.go
- api/billingd/migrations/migrations.go
- api/billingd/service/service.go
- api/bucketsd/service.go
- api/hubd/service.go
- api/usersd/service.go
- buckets/archive/tracker.go
- cmd/buckd/Dockerfile
- cmd/buckd/Dockerfile.dev
- cmd/buckd/docker-compose-dev.yml
- cmd/buckd/docker-compose.yml
- cmd/buckd/main.go
- cmd/hubd/Dockerfile
- cmd/hubd/Dockerfile.dev
- cmd/hubd/docker-compose-dev.yml
- cmd/hubd/docker-compose.yml
- cmd/hubd/main.go
- cmd/output.go
- core/core.go
- dns/dns.go
- email/email.go
- gateway/gateway.go
- go.mod
- ipns/ipns.go
- mongodb/migrations/migrations.go
I've had a local branch with a bunch of docker edits for awhile, but haven't had the time to make a real PR. Here goes...
- This updates all docker images to newer versions of `tini` and `busybox`.
- Properly sets a non-privileged user instead of root and uses its home dir as the data dir (same dir, just now it's the user home as well).
- Now, doing `make hub-up` or `make buck-up` will leverage new development images that allow for remote debugging by using a `dlv` based `ENTRYPOINT` and some additional `-gcflags`. Start a debug session with [delve](https://github.com/go-delve/delve), or via an IDE (GoLand shown below). Using the dev docker compose files, the `textile` and `buckets` services exposes port `40000` for debugging (since you wouldn't run them at the same time), and `billing` …
> Update docker images

- cmd/buckd/main.go
- cmd/hubd/main.go
While defining the commands `hubd` and `buckd` the default values for the flag `dnsToken` is not correctly access from the Flags map. Currently, the value `dnsDomain` is used as the default for the flag `dnsToken`.
> Fix default dns token flag

- README.md
- api/bucketsd/client/client.go
- buckets/local/bucket.go
- buckets/local/bucket_test.go
- buckets/local/buckets.go
- buckets/local/buckets_test.go
- buckets/local/diff.go
- buckets/local/list.go
- buckets/local/options.go
- buckets/local/pull.go
- buckets/local/push.go
- buckets/local/repo.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
- cmd/buck/cli/pull.go
- cmd/buck/cli/push.go
- cmd/config.go
Tricky one requested by a few different users.
- Adds some more `init` flags. From `buck init --help`:
```
By default, if the remote bucket exists, remote objects are pulled and merged with local changes.
Use the '--soft' flag to accept all local changes, including deletions.
Use the '--hard' flag to discard all local changes.
```
> Buck init without discarding local changes

- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
Add the flag `--format`. The flag --format accepts a string to define the output format.
Add support for the format 'json'. If the format is set to json the link struct is printed as parsable JSON object.
Add the flag `--json`. The flag `--json` sets the flag --format to json
With this extension, the link command can be used in an automated environment. For example in a CI script.
I think it makes sense to add the flags for other commands as well.
---
*I completely new at go. I do not know if the changes are compliant with the go standards.*
> feat(buck): extend the command links with ability to set the output format

- go.mod
- go.sum
- integrationtest/pg/docker-compose.yml
- integrationtest/pg/powcli/docker-compose-pow.yml
This PR updates the Powergate client and docker-images tags to the official v2.0.0 release.
> update to powergate v2.0.0 official tag

- gateway/ipfs.go
will default to octet stream on any unknown
fixes #509
> feat(gateway): attempts to detect mime type on all data requests

- README.md
- cmd/buck/cli/add.go
Hi folks,
A little typo I think I stumbled upon, the add command is described as `Add adds a UnixFs DAG...` but I think it should say `Adds a UnixFs DAG...` to avoid confusion.
```
Available Commands:
add         Add adds a UnixFs DAG locally at path
archive     Create a Filecoin archive
cat         Cat bucket objects at path
```
Let me know what you think.
> docs(hub): fix hub bucket add description

- gateway/buckets.go
- gateway/ipfs.go
Use an `io.Reader` instead of loading all the content in a slice, which can lead to high RAM usage and potential OOM crashes.
The mime detection still works crafting a new reader to return the full output.
> gateway: use an io.Reader to serve Cid data

- core/core.go
- go.mod
- go.sum
Bump threads to a temporary branch off of [v1.1.0-rc1](https://github.com/textileio/go-threads/releases/tag/v1.1.0-rc1) that ignores thread pulls: https://github.com/textileio/go-threads/commit/37a104610bac77a5dc74153bcae34fd254871114
> Threads: bump to 37a104610bac77a5dc74153bcae34fd254871114

- api/mindexd/store/query.go
This PR fixes an incorrect mapping in a sorting fields, and enables numeric sorting for string values.
> mindex/query: fix sort mapping & numeric sorting

- .bingo/Variables.mk
- .github/workflows/build.yml
- .github/workflows/publish-js-libs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- api/billingd/Dockerfile
- api/billingd/Dockerfile.dev
- api/mindexd/Dockerfile
- api/mindexd/Dockerfile.dev
- cmd/buck/cli/archive.go
- cmd/buck/cli/roles.go
- cmd/buckd/Dockerfile
- cmd/buckd/Dockerfile.dev
- cmd/hub/cli/update.go
- cmd/hub/cli/version.go
- cmd/hubd/Dockerfile
- cmd/hubd/Dockerfile.dev
- cmd/watch.go
- ipns/ipns.go
`hub update` was panicing on my M1 machine because the code here was assuming the release would always be available for current os/arch. I got sucked into some more improvements. 
I spent a little time actually adding the arm64 builds, but ran into an issue with bingo on go 1.16 and some random build errors while testing locally:
```
--> darwin/arm64 error: exit status 2
Stderr: # github.com/textileio/textile/v2/cmd/hub
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/bp/7ygrmpvn1779kd81k0ltmqkm0000gn/T/go-link-502520635/go.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main …
```
> hub: fix update cmd when build not available

- cmd/hub/cli/cli.go
Fixes `apiSecret` key lookup from the viper config.
There are three ways to leverage config values:
1. Flags
```
hub --apiKey=<key> --apiSecret=<secret> threads ls
```
2. Config file
```
api: api.hub.textile.io:443
apiKey: <key>
apiSecret: <secret>
org: <org> // not required
```
3. Environment vars
```
env HUB_APIKEY=<key> HUB_APISECRET=<secret> hub threads ls
```
Viper [lowercases config keys](https://github.com/spf13/viper/blob/master/viper.go#L1079) when binding to env vars, e.g., the var for api secret is `HUB_APISECRET`, not `HUB_API_SECRET`.
This is confusing because in other program configs we are mapping flags to nested config value. Here's an example from `hubd`:
```
"addrApi": {
Key:      "addr.api",
DefValue: "/ip4/127.0.0.1/tcp/3006",
},
```
That will map to an env var of …
> hub: fix typo in apisecret lookup

- .github/workflows/docker.yml
On pushes to master, generate 2 container images
- update `latest` tag with master commit (I will remove from Docker builds)
- create new image tag, `sha-{{ git short sha}}` , that will be used for a staging deployment
Signed-off-by: Ben Wilson <ben@textile.io>
> Github actions to build docker images for CD

- gateway/buckets.go
- gateway/ipfs.go
based on the suggestion here https://forum.golangbridge.org/t/detectcontenttype-return-wrong-content-type/2922
not comprehensive in any way, just trying to fix incorrect CSS handling in firefox
> fix(css): adds ext detection back for css

- .github/workflows/docker.yml
The matrix list name, `imageRepo` in this case, must match a field in the includes. Otherwise, it just uses 1 value for all iterations.
Signed-off-by: Ben Wilson <ben@textile.io>
> Docker Github action matrix imageRepo fix

- api/bucketsd/service.go
- api/usersd/service.go
- buckets/archive/retrieval/retrieval.go
- buckets/archive/tracker/tracker.go
- cmd/buck/cli/cli.go
- cmd/buck/cli/init.go
- cmd/hub/cli/archives.go
- cmd/hub/cli/cli.go
- cmd/hub/cli/fil_index.go
- cmd/hub/cli/retrievals.go
- cmd/hubd/main.go
- integrationtest/pg/docker-compose.yml
- integrationtest/pg/pg_test.go
- integrationtest/pg/pow_client_test.go
- integrationtest/pg/powergate.go
- threaddb/buckets.go
This PR sits on top of https://github.com/textileio/powergate/pull/807
We had this feature hidden because of a [problem](https://github.com/filecoin-project/lotus/issues/5361) when configuring Lotus when using `IpfsOnlineMode=true`, which didn't make retrievals possible. The Powergate PR workaround this problem, and unblocks the feature.
This PR also added some extra fixes and sections in the Miner Index CLI.
> Enable Filecoin retrievals in Buckets

- api/bucketsd/service.go
- mongodb/bucketarchives.go
- mongodb/migrations/migrations.go
- mongodb/migrations/migrations_test.go
Took over this PR to implement the actual fixes for the following issues uncovered recently:
- The bucket archive bson key `job_status` was changed to `status` months ago, but no migration was done, leaving affected buckets in a state where their `unspecified` current archive status was preventing a new archive from being triggered.
- Hub's Powergate was reset at some point, loosing old archive data. This resulted in old bucket archive storage info from being looked up in Powergate during the creation of a new archive, so the process would fail.
There is one more issue I'm hoping to figure out today, old buckets not deleting, but still need more info from Cake and to do more research there. Maybe we just move forward with these current fixes for now.
> Old Bucket Archive Fixes

- gateway/ipfs.go
in our app, .svg's were not displaying in img tags due to the
content-type returned by the server being `text/plain` instead of
`image/svg+xml`.
To fix, the gateway will return the appropriate content-type,
`image/svg+xml`, for .svg files. As a bonus, .json files will
return `application/json`.
referenced mime types from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
> feat(api): adds content-types for .svg and .json

- .github/weekly-digest.yml
- .github/workflows/test.yml
- api/hubd/client/client.go
- core/core.go
- core/thread_interceptor.go
- core/thread_interceptor_test.go
- go.mod
- go.sum
The thread id that was being checked for caller ownership is from the context, but `go-threads` methods take the id as a param. This was being extracted in some cases, but not for the primary owner check.
> core: fix thread_interceptor owner check

- api/hubd/service.go
This PR forces returning an error on the `Signup` RPC service.
This is done in the context of our plan to shut down the Hub.
Note: some tests are expected to fail since they rely on the signup service doing the expected work since it isn't a feature of the hub to disable signups. I'd like to fix the tests, but the way they're wired, they need complicated local setups. In any case, this change can't break any invariant, and this project will be terminated soon anyway.
> signups: disable them
